CREATE TABLE games (id INT AUTO_INCREMENT NOT NULL, team_1_id INT DEFAULT NULL, team_2_id INT DEFAULT NULL, played TINYINT(1) NOT NULL, INDEX IDX_FF232B312132A881 (team_1_id), INDEX IDX_FF232B313387076F (team_2_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
CREATE TABLE teams (id INT AUTO_INCREMENT NOT NULL, country VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB;
ALTER TABLE games ADD CONSTRAINT FK_FF232B312132A881 FOREIGN KEY (team_1_id) REFERENCES teams (id);
ALTER TABLE games ADD CONSTRAINT FK_FF232B313387076F FOREIGN KEY (team_2_id) REFERENCES teams (id);
